apiVersion: v1
kind: Service
metadata:
  name: opendox-postgres
  namespace: opendox
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: opendox-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
